language: python

sudo: false

python:
  - "3.6"

env:
  - TOX_ENV=py27-django111
  - TOX_ENV=py36-django111

cache:
  - pip

install:
  - pip install tox
  - pip install codecov

script:
  - tox -e $TOX_ENV
